/* Generated by Cython 0.9.8.1.1 on Wed Oct 29 22:24:19 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       Py_ssize_t len;
       int readonly;
       const char *format;
       int ndim;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       Py_ssize_t itemsize;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__pyutmp__pyutmp_bsd
#include "sys/types.h"
#include "utmp.h"
#include "fcntl.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */
/* Module declarations from pyutmp.pyutmp_bsd */



/* Implementation of pyutmp.pyutmp_bsd */
static PyObject *__pyx_int_neg_1;
static char __pyx_k_Utmp[] = "Utmp";
static PyObject *__pyx_kp_Utmp;
static char __pyx_k_object[] = "object";
static PyObject *__pyx_kp_object;
static char __pyx_k_ut_line[] = "ut_line";
static PyObject *__pyx_kp_ut_line;
static char __pyx_k_ut_user[] = "ut_user";
static PyObject *__pyx_kp_ut_user;
static char __pyx_k_ut_host[] = "ut_host";
static PyObject *__pyx_kp_ut_host;
static char __pyx_k_ut_time[] = "ut_time";
static PyObject *__pyx_kp_ut_time;
static char __pyx_k_ut_user_process[] = "ut_user_process";
static PyObject *__pyx_kp_ut_user_process;
static char __pyx_k__UtmpFile[] = "_UtmpFile";
static PyObject *__pyx_kp__UtmpFile;
static char __pyx_k___init__[] = "__init__";
static PyObject *__pyx_kp___init__;
static char __pyx_k___del__[] = "__del__";
static PyObject *__pyx_kp___del__;
static char __pyx_k_rewind[] = "rewind";
static PyObject *__pyx_kp_rewind;
static char __pyx_k__get_next_entry[] = "_get_next_entry";
static PyObject *__pyx_kp__get_next_entry;
static char __pyx_k_items[] = "items";
static PyObject *__pyx_kp_items;
static char __pyx_k__fd[] = "_fd";
static PyObject *__pyx_kp__fd;
static char __pyx_k_startswith[] = "startswith";
static PyObject *__pyx_kp_startswith;
static PyObject *__pyx_builtin_object;
static PyObject *__pyx_kp_4;
static PyObject *__pyx_kp_5;
static char __pyx_k_1[] = "\000";
static char __pyx_k_2[] = "\000";
static char __pyx_k_3[] = "\000";
static char __pyx_k_4[] = "/";
static char __pyx_k_5[] = "/dev/";

/* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":59
 * class _UtmpFile(object):
 * 
 *     def __init__(self, path=None):             # <<<<<<<<<<<<<<
 *         if not path:
 *             path = _PATH_UTMP
 */

static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile___init__ = {"__init__", (PyCFunction)__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_path = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  char *__pyx_4;
  static char *__pyx_argnames[] = {"self","path",0};
  __pyx_self = __pyx_self;
  __pyx_v_path = Py_None;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_self = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_path = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_self, &__pyx_v_path))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4;
  __pyx_L3_error:;
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd._UtmpFile.__init__");
  return NULL;
  __pyx_L4:;
  Py_INCREF(__pyx_v_path);

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":60
 * 
 *     def __init__(self, path=None):
 *         if not path:             # <<<<<<<<<<<<<<
 *             path = _PATH_UTMP
 *         self._fd = open(path, O_RDONLY, 0)
 */
  __pyx_1 = __Pyx_PyObject_IsTrue(__pyx_v_path); if (unlikely(__pyx_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = (!__pyx_1);
  if (__pyx_2) {

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":61
 *     def __init__(self, path=None):
 *         if not path:
 *             path = _PATH_UTMP             # <<<<<<<<<<<<<<
 *         self._fd = open(path, O_RDONLY, 0)
 * 
 */
    __pyx_3 = __Pyx_PyBytes_FromString(_PATH_UTMP); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_v_path);
    __pyx_v_path = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":62
 *         if not path:
 *             path = _PATH_UTMP
 *         self._fd = open(path, O_RDONLY, 0)             # <<<<<<<<<<<<<<
 * 
 *     def __del__(self):
 */
  __pyx_4 = __Pyx_PyBytes_AsString(__pyx_v_path); if (unlikely((!__pyx_4) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyInt_FromLong(open(__pyx_4, O_RDONLY, 0)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_v_self, __pyx_kp__fd, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd._UtmpFile.__init__");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_path);
  return __pyx_r;
}

/* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":64
 *         self._fd = open(path, O_RDONLY, 0)
 * 
 *     def __del__(self):             # <<<<<<<<<<<<<<
 *         close(self._fd)
 * 
 */

static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile___del__(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile___del__ = {"__del__", (PyCFunction)__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile___del__, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile___del__(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  __pyx_self = __pyx_self;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":65
 * 
 *     def __del__(self):
 *         close(self._fd)             # <<<<<<<<<<<<<<
 * 
 *     def rewind(self):
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_kp__fd); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __pyx_PyInt_int(__pyx_1); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  close(__pyx_2);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd._UtmpFile.__del__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":67
 *         close(self._fd)
 * 
 *     def rewind(self):             # <<<<<<<<<<<<<<
 *         lseek(self._fd, 0, SEEK_SET)
 * 
 */

static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile_rewind(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile_rewind = {"rewind", (PyCFunction)__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile_rewind, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile_rewind(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  __pyx_self = __pyx_self;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":68
 * 
 *     def rewind(self):
 *         lseek(self._fd, 0, SEEK_SET)             # <<<<<<<<<<<<<<
 * 
 *     def _get_next_entry(self):
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_kp__fd); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __pyx_PyInt_int(__pyx_1); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  lseek(__pyx_2, 0, SEEK_SET);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd._UtmpFile.rewind");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":70
 *         lseek(self._fd, 0, SEEK_SET)
 * 
 *     def _get_next_entry(self):             # <<<<<<<<<<<<<<
 *         cdef utmp entry
 *         cdef int bytes
 */

static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile__get_next_entry(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile__get_next_entry = {"_get_next_entry", (PyCFunction)__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile__get_next_entry, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile__get_next_entry(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  struct utmp __pyx_v_entry;
  int __pyx_v_bytes;
  PyObject *__pyx_v_u;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  Py_ssize_t __pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  __pyx_self = __pyx_self;
  __pyx_v_u = Py_None; Py_INCREF(Py_None);

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":74
 *         cdef int bytes
 * 
 *         bytes = read(self._fd, &entry, sizeof(entry))             # <<<<<<<<<<<<<<
 *         if bytes > 0:
 *             entry.ut_host[UT_HOSTSIZE - 1] = '\0'
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_kp__fd); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __pyx_PyInt_int(__pyx_1); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_bytes = read(__pyx_2, (&__pyx_v_entry), (sizeof(__pyx_v_entry)));

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":75
 * 
 *         bytes = read(self._fd, &entry, sizeof(entry))
 *         if bytes > 0:             # <<<<<<<<<<<<<<
 *             entry.ut_host[UT_HOSTSIZE - 1] = '\0'
 *             entry.ut_line[UT_LINESIZE - 1] = '\0'
 */
  __pyx_3 = (__pyx_v_bytes > 0);
  if (__pyx_3) {

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":76
 *         bytes = read(self._fd, &entry, sizeof(entry))
 *         if bytes > 0:
 *             entry.ut_host[UT_HOSTSIZE - 1] = '\0'             # <<<<<<<<<<<<<<
 *             entry.ut_line[UT_LINESIZE - 1] = '\0'
 *             entry.ut_name[UT_NAMESIZE - 1] = '\0'
 */
    (__pyx_v_entry.ut_host[(UT_HOSTSIZE - 1)]) = '\x00';

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":77
 *         if bytes > 0:
 *             entry.ut_host[UT_HOSTSIZE - 1] = '\0'
 *             entry.ut_line[UT_LINESIZE - 1] = '\0'             # <<<<<<<<<<<<<<
 *             entry.ut_name[UT_NAMESIZE - 1] = '\0'
 *             u = Utmp()
 */
    (__pyx_v_entry.ut_line[(UT_LINESIZE - 1)]) = '\x00';

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":78
 *             entry.ut_host[UT_HOSTSIZE - 1] = '\0'
 *             entry.ut_line[UT_LINESIZE - 1] = '\0'
 *             entry.ut_name[UT_NAMESIZE - 1] = '\0'             # <<<<<<<<<<<<<<
 *             u = Utmp()
 *             u.ut_user_process = len(entry.ut_name) > 0
 */
    (__pyx_v_entry.ut_name[(UT_NAMESIZE - 1)]) = '\x00';

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":79
 *             entry.ut_line[UT_LINESIZE - 1] = '\0'
 *             entry.ut_name[UT_NAMESIZE - 1] = '\0'
 *             u = Utmp()             # <<<<<<<<<<<<<<
 *             u.ut_user_process = len(entry.ut_name) > 0
 *             u.ut_time = entry.ut_time
 */
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_Utmp); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_4 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_v_u);
    __pyx_v_u = __pyx_4;
    __pyx_4 = 0;

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":80
 *             entry.ut_name[UT_NAMESIZE - 1] = '\0'
 *             u = Utmp()
 *             u.ut_user_process = len(entry.ut_name) > 0             # <<<<<<<<<<<<<<
 *             u.ut_time = entry.ut_time
 * 
 */
    __pyx_1 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_name); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_5 = PyObject_Length(__pyx_1); if (unlikely(__pyx_5 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = __Pyx_PyBool_FromLong((__pyx_5 > 0)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_user_process, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":81
 *             u = Utmp()
 *             u.ut_user_process = len(entry.ut_name) > 0
 *             u.ut_time = entry.ut_time             # <<<<<<<<<<<<<<
 * 
 *             if len(entry.ut_name) > 0:
 */
    __pyx_1 = PyInt_FromLong(__pyx_v_entry.ut_time); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_time, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":83
 *             u.ut_time = entry.ut_time
 * 
 *             if len(entry.ut_name) > 0:             # <<<<<<<<<<<<<<
 *                 u.ut_user = entry.ut_name
 *             else:
 */
    __pyx_4 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_name); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_5 = PyObject_Length(__pyx_4); if (unlikely(__pyx_5 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = (__pyx_5 > 0);
    if (__pyx_3) {

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":84
 * 
 *             if len(entry.ut_name) > 0:
 *                 u.ut_user = entry.ut_name             # <<<<<<<<<<<<<<
 *             else:
 *                 u.ut_user = None
 */
      __pyx_1 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_name); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_user, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      goto __pyx_L6;
    }
    /*else*/ {

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":86
 *                 u.ut_user = entry.ut_name
 *             else:
 *                 u.ut_user = None             # <<<<<<<<<<<<<<
 * 
 *             if len(entry.ut_line) == 0:
 */
      if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_user, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    __pyx_L6:;

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":88
 *                 u.ut_user = None
 * 
 *             if len(entry.ut_line) == 0:             # <<<<<<<<<<<<<<
 *                 u.ut_line = None
 *             else:
 */
    __pyx_4 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_line); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_5 = PyObject_Length(__pyx_4); if (unlikely(__pyx_5 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = (__pyx_5 == 0);
    if (__pyx_3) {

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":89
 * 
 *             if len(entry.ut_line) == 0:
 *                 u.ut_line = None             # <<<<<<<<<<<<<<
 *             else:
 *                 u.ut_line = entry.ut_line
 */
      if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_line, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      goto __pyx_L7;
    }
    /*else*/ {

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":91
 *                 u.ut_line = None
 *             else:
 *                 u.ut_line = entry.ut_line             # <<<<<<<<<<<<<<
 *                 if not u.ut_line.startswith('/'):
 *                     u.ut_line = '/dev/' + u.ut_line
 */
      __pyx_1 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_line); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_line, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":92
 *             else:
 *                 u.ut_line = entry.ut_line
 *                 if not u.ut_line.startswith('/'):             # <<<<<<<<<<<<<<
 *                     u.ut_line = '/dev/' + u.ut_line
 * 
 */
      __pyx_4 = PyObject_GetAttr(__pyx_v_u, __pyx_kp_ut_line); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __pyx_1 = PyObject_GetAttr(__pyx_4, __pyx_kp_startswith); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_INCREF(__pyx_kp_4);
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_kp_4);
      __pyx_6 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
      __pyx_3 = __Pyx_PyObject_IsTrue(__pyx_6); if (unlikely(__pyx_3 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __pyx_7 = (!__pyx_3);
      if (__pyx_7) {

        /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":93
 *                 u.ut_line = entry.ut_line
 *                 if not u.ut_line.startswith('/'):
 *                     u.ut_line = '/dev/' + u.ut_line             # <<<<<<<<<<<<<<
 * 
 *             if len(entry.ut_host) > 0:
 */
        __pyx_1 = PyObject_GetAttr(__pyx_v_u, __pyx_kp_ut_line); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __pyx_4 = PyNumber_Add(__pyx_kp_5, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_line, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        goto __pyx_L8;
      }
      __pyx_L8:;
    }
    __pyx_L7:;

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":95
 *                     u.ut_line = '/dev/' + u.ut_line
 * 
 *             if len(entry.ut_host) > 0:             # <<<<<<<<<<<<<<
 *                 u.ut_host = entry.ut_host
 *             else:
 */
    __pyx_6 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_host); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_5 = PyObject_Length(__pyx_6); if (unlikely(__pyx_5 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_3 = (__pyx_5 > 0);
    if (__pyx_3) {

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":96
 * 
 *             if len(entry.ut_host) > 0:
 *                 u.ut_host = entry.ut_host             # <<<<<<<<<<<<<<
 *             else:
 *                 u.ut_host = None
 */
      __pyx_1 = __Pyx_PyBytes_FromString(__pyx_v_entry.ut_host); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_host, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      goto __pyx_L9;
    }
    /*else*/ {

      /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":98
 *                 u.ut_host = entry.ut_host
 *             else:
 *                 u.ut_host = None             # <<<<<<<<<<<<<<
 * 
 *         else:
 */
      if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_host, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    __pyx_L9:;
    goto __pyx_L5;
  }
  /*else*/ {

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":101
 * 
 *         else:
 *             u = None             # <<<<<<<<<<<<<<
 *             close(self._fd)
 *             self._fd = -1
 */
    Py_INCREF(Py_None);
    Py_DECREF(__pyx_v_u);
    __pyx_v_u = Py_None;

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":102
 *         else:
 *             u = None
 *             close(self._fd)             # <<<<<<<<<<<<<<
 *             self._fd = -1
 * 
 */
    __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_kp__fd); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_2 = __pyx_PyInt_int(__pyx_4); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    close(__pyx_2);

    /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":103
 *             u = None
 *             close(self._fd)
 *             self._fd = -1             # <<<<<<<<<<<<<<
 * 
 *         return u
 */
    if (PyObject_SetAttr(__pyx_v_self, __pyx_kp__fd, __pyx_int_neg_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  __pyx_L5:;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":105
 *             self._fd = -1
 * 
 *         return u             # <<<<<<<<<<<<<<
 * 
 *     def items(self):
 */
  Py_INCREF(__pyx_v_u);
  __pyx_r = __pyx_v_u;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd._UtmpFile._get_next_entry");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_u);
  return __pyx_r;
}

/* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":107
 *         return u
 * 
 *     def items(self):             # <<<<<<<<<<<<<<
 *         return [item for item in self]
 * 
 */

static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile_items(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile_items = {"items", (PyCFunction)__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile_items, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_10pyutmp_bsd_9_UtmpFile_items(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_v_item;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  __pyx_self = __pyx_self;
  __pyx_v_item = Py_None; Py_INCREF(Py_None);

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":108
 * 
 *     def items(self):
 *         return [item for item in self]             # <<<<<<<<<<<<<<
 * 
 */
  __pyx_1 = PyList_New(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyList_CheckExact(__pyx_v_self) || PyTuple_CheckExact(__pyx_v_self)) {
    __pyx_2 = 0; __pyx_3 = __pyx_v_self; Py_INCREF(__pyx_3);
  } else {
    __pyx_2 = -1; __pyx_3 = PyObject_GetIter(__pyx_v_self); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  for (;;) {
    if (likely(PyList_CheckExact(__pyx_3))) {
      if (__pyx_2 >= PyList_GET_SIZE(__pyx_3)) break;
      __pyx_4 = PyList_GET_ITEM(__pyx_3, __pyx_2); Py_INCREF(__pyx_4); __pyx_2++;
    } else if (likely(PyTuple_CheckExact(__pyx_3))) {
      if (__pyx_2 >= PyTuple_GET_SIZE(__pyx_3)) break;
      __pyx_4 = PyTuple_GET_ITEM(__pyx_3, __pyx_2); Py_INCREF(__pyx_4); __pyx_2++;
    } else {
      __pyx_4 = PyIter_Next(__pyx_3);
      if (!__pyx_4) {
        if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        break;
      }
    }
    Py_DECREF(__pyx_v_item);
    __pyx_v_item = __pyx_4;
    __pyx_4 = 0;
    __pyx_5 = PyList_Append(__pyx_1, __pyx_v_item); if (unlikely(__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = ((PyObject *)__pyx_1);
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd._UtmpFile.items");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_item);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "pyutmp_bsd",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_Utmp, __pyx_k_Utmp, sizeof(__pyx_k_Utmp), 0, 1, 1},
  {&__pyx_kp_object, __pyx_k_object, sizeof(__pyx_k_object), 1, 1, 1},
  {&__pyx_kp_ut_line, __pyx_k_ut_line, sizeof(__pyx_k_ut_line), 1, 1, 1},
  {&__pyx_kp_ut_user, __pyx_k_ut_user, sizeof(__pyx_k_ut_user), 1, 1, 1},
  {&__pyx_kp_ut_host, __pyx_k_ut_host, sizeof(__pyx_k_ut_host), 1, 1, 1},
  {&__pyx_kp_ut_time, __pyx_k_ut_time, sizeof(__pyx_k_ut_time), 1, 1, 1},
  {&__pyx_kp_ut_user_process, __pyx_k_ut_user_process, sizeof(__pyx_k_ut_user_process), 1, 1, 1},
  {&__pyx_kp__UtmpFile, __pyx_k__UtmpFile, sizeof(__pyx_k__UtmpFile), 0, 1, 1},
  {&__pyx_kp___init__, __pyx_k___init__, sizeof(__pyx_k___init__), 0, 1, 1},
  {&__pyx_kp___del__, __pyx_k___del__, sizeof(__pyx_k___del__), 0, 1, 1},
  {&__pyx_kp_rewind, __pyx_k_rewind, sizeof(__pyx_k_rewind), 0, 1, 1},
  {&__pyx_kp__get_next_entry, __pyx_k__get_next_entry, sizeof(__pyx_k__get_next_entry), 0, 1, 1},
  {&__pyx_kp_items, __pyx_k_items, sizeof(__pyx_k_items), 0, 1, 1},
  {&__pyx_kp__fd, __pyx_k__fd, sizeof(__pyx_k__fd), 1, 1, 1},
  {&__pyx_kp_startswith, __pyx_k_startswith, sizeof(__pyx_k_startswith), 1, 1, 1},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 0, 0, 0},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  __pyx_builtin_object = __Pyx_GetName(__pyx_b, __pyx_kp_object); if (!__pyx_builtin_object) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  return 0;
  __pyx_L1_error:;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  __pyx_int_neg_1 = PyInt_FromLong(-1); if (unlikely(!__pyx_int_neg_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyutmp_bsd(void); /*proto*/
PyMODINIT_FUNC initpyutmp_bsd(void)
#else
PyMODINIT_FUNC PyInit_pyutmp_bsd(void); /*proto*/
PyMODINIT_FUNC PyInit_pyutmp_bsd(void)
#endif
{
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("pyutmp_bsd", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":50
 *         O_RDWR   = 2
 * 
 * class Utmp(object):             # <<<<<<<<<<<<<<
 *     ut_line = None
 *     ut_user = None
 */
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_builtin_object);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_builtin_object);
  __pyx_3 = __Pyx_CreateClass(((PyObject *)__pyx_2), ((PyObject *)__pyx_1), __pyx_kp_Utmp, "pyutmp.pyutmp_bsd"); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":51
 * 
 * class Utmp(object):
 *     ut_line = None             # <<<<<<<<<<<<<<
 *     ut_user = None
 *     ut_host = None
 */
  if (PyObject_SetAttr(__pyx_3, __pyx_kp_ut_line, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":52
 * class Utmp(object):
 *     ut_line = None
 *     ut_user = None             # <<<<<<<<<<<<<<
 *     ut_host = None
 *     ut_time = None
 */
  if (PyObject_SetAttr(__pyx_3, __pyx_kp_ut_user, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":53
 *     ut_line = None
 *     ut_user = None
 *     ut_host = None             # <<<<<<<<<<<<<<
 *     ut_time = None
 *     ut_user_process = False
 */
  if (PyObject_SetAttr(__pyx_3, __pyx_kp_ut_host, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":54
 *     ut_user = None
 *     ut_host = None
 *     ut_time = None             # <<<<<<<<<<<<<<
 *     ut_user_process = False
 * 
 */
  if (PyObject_SetAttr(__pyx_3, __pyx_kp_ut_time, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":55
 *     ut_host = None
 *     ut_time = None
 *     ut_user_process = False             # <<<<<<<<<<<<<<
 * 
 * class _UtmpFile(object):
 */
  __pyx_2 = __Pyx_PyBool_FromLong(0); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_3, __pyx_kp_ut_user_process, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_Utmp, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":57
 *     ut_user_process = False
 * 
 * class _UtmpFile(object):             # <<<<<<<<<<<<<<
 * 
 *     def __init__(self, path=None):
 */
  __pyx_2 = PyDict_New(); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_builtin_object);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_builtin_object);
  __pyx_1 = __Pyx_CreateClass(((PyObject *)__pyx_3), ((PyObject *)__pyx_2), __pyx_kp__UtmpFile, "pyutmp.pyutmp_bsd"); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":59
 * class _UtmpFile(object):
 * 
 *     def __init__(self, path=None):             # <<<<<<<<<<<<<<
 *         if not path:
 *             path = _PATH_UTMP
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile___init__, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_kp___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":64
 *         self._fd = open(path, O_RDONLY, 0)
 * 
 *     def __del__(self):             # <<<<<<<<<<<<<<
 *         close(self._fd)
 * 
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile___del__, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_kp___del__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":67
 *         close(self._fd)
 * 
 *     def rewind(self):             # <<<<<<<<<<<<<<
 *         lseek(self._fd, 0, SEEK_SET)
 * 
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile_rewind, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_kp_rewind, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":70
 *         lseek(self._fd, 0, SEEK_SET)
 * 
 *     def _get_next_entry(self):             # <<<<<<<<<<<<<<
 *         cdef utmp entry
 *         cdef int bytes
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile__get_next_entry, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_kp__get_next_entry, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_bsd.pyx":107
 *         return u
 * 
 *     def items(self):             # <<<<<<<<<<<<<<
 *         return [item for item in self]
 * 
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_10pyutmp_bsd_9_UtmpFile_items, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_kp_items, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp__UtmpFile, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyutmp.pyutmp_bsd");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "pyutmp_bsd.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;

    #if PY_MAJOR_VERSION < 3
    py_modname = PyString_FromString(modname);
    #else
    py_modname = PyUnicode_FromString(modname);
    #endif
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    result = PyClass_New(bases, dict, name);
    #else
    result = PyObject_CallFunctionObjArgs((PyObject *)&PyType_Type, name, bases, dict, NULL);
    #endif
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

