/* Generated by Cython 0.9.8.1.1 on Wed Oct 29 19:43:00 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       Py_ssize_t len;
       int readonly;
       const char *format;
       int ndim;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       Py_ssize_t itemsize;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__pyutmp__pyutmp_sysv
#include "time.h"
#include "utmp.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static INLINE PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i, int is_unsigned) {
    PyObject *r;
    if (PyList_CheckExact(o) && 0 <= i && i < PyList_GET_SIZE(o)) {
        r = PyList_GET_ITEM(o, i);
        Py_INCREF(r);
    }
    else if (PyTuple_CheckExact(o) && 0 <= i && i < PyTuple_GET_SIZE(o)) {
        r = PyTuple_GET_ITEM(o, i);
        Py_INCREF(r);
    }
    else if (Py_TYPE(o)->tp_as_sequence && Py_TYPE(o)->tp_as_sequence->sq_item && (likely(i >= 0) || !is_unsigned))
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = (likely(i >= 0) || !is_unsigned) ? PyInt_FromLong(i) : PyLong_FromUnsignedLongLong((sizeof(unsigned long long) > sizeof(Py_ssize_t) ? (1ULL << (sizeof(Py_ssize_t)*8)) : 0) + i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */
/* Module declarations from pyutmp.pyutmp_sysv */



/* Implementation of pyutmp.pyutmp_sysv */
static PyObject *__pyx_int_0;
static char __pyx_k_enum[] = "enum";
static PyObject *__pyx_kp_enum;
static char __pyx_k_Enum[] = "Enum";
static PyObject *__pyx_kp_Enum;
static char __pyx_k_1[] = "RUN_LVL";
static PyObject *__pyx_kp_1;
static char __pyx_k_2[] = "BOOT_TIME";
static PyObject *__pyx_kp_2;
static char __pyx_k_3[] = "NEW_TIME";
static PyObject *__pyx_kp_3;
static char __pyx_k_4[] = "OLD_TIME";
static PyObject *__pyx_kp_4;
static char __pyx_k_5[] = "INIT_PROCESS";
static PyObject *__pyx_kp_5;
static char __pyx_k_6[] = "LOGIN_PROCESS";
static PyObject *__pyx_kp_6;
static char __pyx_k_7[] = "USER_PROCESS";
static PyObject *__pyx_kp_7;
static char __pyx_k_8[] = "DEAD_PROCESS";
static PyObject *__pyx_kp_8;
static char __pyx_k_9[] = "ACCOUNTING";
static PyObject *__pyx_kp_9;
static char __pyx_k_UT_TYPE[] = "UT_TYPE";
static PyObject *__pyx_kp_UT_TYPE;
static char __pyx_k_10[] = "RUN_LVL";
static PyObject *__pyx_kp_10;
static char __pyx_k_11[] = "BOOT_TIME";
static PyObject *__pyx_kp_11;
static char __pyx_k_12[] = "NEW_TIME";
static PyObject *__pyx_kp_12;
static char __pyx_k_13[] = "OLD_TIME";
static PyObject *__pyx_kp_13;
static char __pyx_k_14[] = "INIT_PROCESS";
static PyObject *__pyx_kp_14;
static char __pyx_k_15[] = "LOGIN_PROCESS";
static PyObject *__pyx_kp_15;
static char __pyx_k_16[] = "USER_PROCESS";
static PyObject *__pyx_kp_16;
static char __pyx_k_17[] = "DEAD_PROCESS";
static PyObject *__pyx_kp_17;
static char __pyx_k_18[] = "ACCOUNTING";
static PyObject *__pyx_kp_18;
static char __pyx_k__TYPE_MAP[] = "_TYPE_MAP";
static PyObject *__pyx_kp__TYPE_MAP;
static char __pyx_k_Utmp[] = "Utmp";
static PyObject *__pyx_kp_Utmp;
static char __pyx_k_object[] = "object";
static PyObject *__pyx_kp_object;
static char __pyx_k_ut_type[] = "ut_type";
static PyObject *__pyx_kp_ut_type;
static char __pyx_k_ut_pid[] = "ut_pid";
static PyObject *__pyx_kp_ut_pid;
static char __pyx_k_ut_line[] = "ut_line";
static PyObject *__pyx_kp_ut_line;
static char __pyx_k_ut_id[] = "ut_id";
static PyObject *__pyx_kp_ut_id;
static char __pyx_k_ut_user[] = "ut_user";
static PyObject *__pyx_kp_ut_user;
static char __pyx_k_ut_host[] = "ut_host";
static PyObject *__pyx_kp_ut_host;
static char __pyx_k_ut_exit_code[] = "ut_exit_code";
static PyObject *__pyx_kp_ut_exit_code;
static char __pyx_k_ut_session[] = "ut_session";
static PyObject *__pyx_kp_ut_session;
static char __pyx_k_ut_time[] = "ut_time";
static PyObject *__pyx_kp_ut_time;
static char __pyx_k_ut_addr[] = "ut_addr";
static PyObject *__pyx_kp_ut_addr;
static char __pyx_k_ut_user_process[] = "ut_user_process";
static PyObject *__pyx_kp_ut_user_process;
static char __pyx_k_pyutmp[] = "pyutmp";
static PyObject *__pyx_kp_pyutmp;
static char __pyx_k_UtmpFileBase[] = "UtmpFileBase";
static PyObject *__pyx_kp_UtmpFileBase;
static char __pyx_k_UtmpFile[] = "UtmpFile";
static PyObject *__pyx_kp_UtmpFile;
static char __pyx_k___init__[] = "__init__";
static PyObject *__pyx_kp___init__;
static char __pyx_k___del__[] = "__del__";
static PyObject *__pyx_kp___del__;
static char __pyx_k_rewind[] = "rewind";
static PyObject *__pyx_kp_rewind;
static char __pyx_k__get_next_entry[] = "_get_next_entry";
static PyObject *__pyx_kp__get_next_entry;
static char __pyx_k_19[] = "USER_PROCESS";
static PyObject *__pyx_kp_19;
static PyObject *__pyx_builtin_object;

/* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":89
 * class UtmpFile(UtmpFileBase):
 * 
 *     def __init__(self):             # <<<<<<<<<<<<<<
 *         setutent()
 * 
 */

static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile___init__(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile___init__ = {"__init__", (PyCFunction)__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile___init__, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile___init__(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  __pyx_self = __pyx_self;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":90
 * 
 *     def __init__(self):
 *         setutent()             # <<<<<<<<<<<<<<
 * 
 *     def __del__(self):
 */
  setutent();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":92
 *         setutent()
 * 
 *     def __del__(self):             # <<<<<<<<<<<<<<
 *         endutent()
 * 
 */

static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile___del__(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile___del__ = {"__del__", (PyCFunction)__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile___del__, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile___del__(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  __pyx_self = __pyx_self;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":93
 * 
 *     def __del__(self):
 *         endutent()             # <<<<<<<<<<<<<<
 * 
 *     def rewind(self):
 */
  endutent();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":95
 *         endutent()
 * 
 *     def rewind(self):             # <<<<<<<<<<<<<<
 *         setutent()
 * 
 */

static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile_rewind(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile_rewind = {"rewind", (PyCFunction)__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile_rewind, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile_rewind(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  __pyx_self = __pyx_self;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":96
 * 
 *     def rewind(self):
 *         setutent()             # <<<<<<<<<<<<<<
 * 
 *     def _get_next_entry(self):
 */
  setutent();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":98
 *         setutent()
 * 
 *     def _get_next_entry(self):             # <<<<<<<<<<<<<<
 *         cdef utmp *entry = getutent()
 *         if entry:
 */

static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile__get_next_entry(PyObject *__pyx_self, PyObject *__pyx_v_self); /*proto*/
static PyMethodDef __pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile__get_next_entry = {"_get_next_entry", (PyCFunction)__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile__get_next_entry, METH_O, 0};
static PyObject *__pyx_pf_6pyutmp_11pyutmp_sysv_8UtmpFile__get_next_entry(PyObject *__pyx_self, PyObject *__pyx_v_self) {
  struct utmp *__pyx_v_entry;
  PyObject *__pyx_v_u;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_self = __pyx_self;
  __pyx_v_u = Py_None; Py_INCREF(Py_None);

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":99
 * 
 *     def _get_next_entry(self):
 *         cdef utmp *entry = getutent()             # <<<<<<<<<<<<<<
 *         if entry:
 *             u = Utmp()
 */
  __pyx_v_entry = getutent();

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":100
 *     def _get_next_entry(self):
 *         cdef utmp *entry = getutent()
 *         if entry:             # <<<<<<<<<<<<<<
 *             u = Utmp()
 *             u.ut_type = _TYPE_MAP[entry.ut_type]
 */
  __pyx_1 = (__pyx_v_entry != 0);
  if (__pyx_1) {

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":101
 *         cdef utmp *entry = getutent()
 *         if entry:
 *             u = Utmp()             # <<<<<<<<<<<<<<
 *             u.ut_type = _TYPE_MAP[entry.ut_type]
 *             u.ut_user_process = (u.ut_type == 'USER_PROCESS')
 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_Utmp); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_u);
    __pyx_v_u = __pyx_3;
    __pyx_3 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":102
 *         if entry:
 *             u = Utmp()
 *             u.ut_type = _TYPE_MAP[entry.ut_type]             # <<<<<<<<<<<<<<
 *             u.ut_user_process = (u.ut_type == 'USER_PROCESS')
 *             u.ut_line = entry.ut_line
 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp__TYPE_MAP); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_3 = __Pyx_GetItemInt(__pyx_2, __pyx_v_entry->ut_type, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_type, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":103
 *             u = Utmp()
 *             u.ut_type = _TYPE_MAP[entry.ut_type]
 *             u.ut_user_process = (u.ut_type == 'USER_PROCESS')             # <<<<<<<<<<<<<<
 *             u.ut_line = entry.ut_line
 *             u.ut_pid = entry.ut_pid
 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_u, __pyx_kp_ut_type); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_3 = PyObject_RichCompare(__pyx_2, __pyx_kp_19, Py_EQ); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_user_process, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":104
 *             u.ut_type = _TYPE_MAP[entry.ut_type]
 *             u.ut_user_process = (u.ut_type == 'USER_PROCESS')
 *             u.ut_line = entry.ut_line             # <<<<<<<<<<<<<<
 *             u.ut_pid = entry.ut_pid
 *             u.ut_id = entry.ut_id
 */
    __pyx_2 = __Pyx_PyBytes_FromString(__pyx_v_entry->ut_line); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_line, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":105
 *             u.ut_user_process = (u.ut_type == 'USER_PROCESS')
 *             u.ut_line = entry.ut_line
 *             u.ut_pid = entry.ut_pid             # <<<<<<<<<<<<<<
 *             u.ut_id = entry.ut_id
 *             u.ut_user = entry.ut_user
 */
    __pyx_3 = PyInt_FromLong(__pyx_v_entry->ut_pid); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_pid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":106
 *             u.ut_line = entry.ut_line
 *             u.ut_pid = entry.ut_pid
 *             u.ut_id = entry.ut_id             # <<<<<<<<<<<<<<
 *             u.ut_user = entry.ut_user
 *             u.ut_host = entry.ut_host
 */
    __pyx_2 = __Pyx_PyBytes_FromString(__pyx_v_entry->ut_id); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_id, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":107
 *             u.ut_pid = entry.ut_pid
 *             u.ut_id = entry.ut_id
 *             u.ut_user = entry.ut_user             # <<<<<<<<<<<<<<
 *             u.ut_host = entry.ut_host
 *             u.ut_exit_code = entry.ut_exit.e_exit
 */
    __pyx_3 = __Pyx_PyBytes_FromString(__pyx_v_entry->ut_user); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_user, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":108
 *             u.ut_id = entry.ut_id
 *             u.ut_user = entry.ut_user
 *             u.ut_host = entry.ut_host             # <<<<<<<<<<<<<<
 *             u.ut_exit_code = entry.ut_exit.e_exit
 *             u.ut_time = float(entry.ut_tv.tv_sec)
 */
    __pyx_2 = __Pyx_PyBytes_FromString(__pyx_v_entry->ut_host); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_host, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":109
 *             u.ut_user = entry.ut_user
 *             u.ut_host = entry.ut_host
 *             u.ut_exit_code = entry.ut_exit.e_exit             # <<<<<<<<<<<<<<
 *             u.ut_time = float(entry.ut_tv.tv_sec)
 *             u.ut_addr = entry.ut_addr_v6[0]
 */
    __pyx_3 = PyInt_FromLong(__pyx_v_entry->ut_exit.e_exit); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_exit_code, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":110
 *             u.ut_host = entry.ut_host
 *             u.ut_exit_code = entry.ut_exit.e_exit
 *             u.ut_time = float(entry.ut_tv.tv_sec)             # <<<<<<<<<<<<<<
 *             u.ut_addr = entry.ut_addr_v6[0]
 *         else:
 */
    __pyx_2 = PyInt_FromLong(__pyx_v_entry->ut_tv.tv_sec); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_Call(((PyObject*)&PyFloat_Type), ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_time, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":111
 *             u.ut_exit_code = entry.ut_exit.e_exit
 *             u.ut_time = float(entry.ut_tv.tv_sec)
 *             u.ut_addr = entry.ut_addr_v6[0]             # <<<<<<<<<<<<<<
 *         else:
 *             u = None
 */
    __pyx_3 = PyInt_FromLong((__pyx_v_entry->ut_addr_v6[0])); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyObject_SetAttr(__pyx_v_u, __pyx_kp_ut_addr, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L5;
  }
  /*else*/ {

    /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":113
 *             u.ut_addr = entry.ut_addr_v6[0]
 *         else:
 *             u = None             # <<<<<<<<<<<<<<
 * 
 *         return u
 */
    Py_INCREF(Py_None);
    Py_DECREF(__pyx_v_u);
    __pyx_v_u = Py_None;
  }
  __pyx_L5:;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":115
 *             u = None
 * 
 *         return u             # <<<<<<<<<<<<<<
 */
  Py_INCREF(__pyx_v_u);
  __pyx_r = __pyx_v_u;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pyutmp.pyutmp_sysv.UtmpFile._get_next_entry");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_u);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "pyutmp_sysv",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_enum, __pyx_k_enum, sizeof(__pyx_k_enum), 1, 1, 1},
  {&__pyx_kp_Enum, __pyx_k_Enum, sizeof(__pyx_k_Enum), 1, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 1, 0},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 0, 1, 0},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 1, 0},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 0, 1, 0},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 0, 1, 0},
  {&__pyx_kp_6, __pyx_k_6, sizeof(__pyx_k_6), 0, 1, 0},
  {&__pyx_kp_7, __pyx_k_7, sizeof(__pyx_k_7), 0, 1, 0},
  {&__pyx_kp_8, __pyx_k_8, sizeof(__pyx_k_8), 0, 1, 0},
  {&__pyx_kp_9, __pyx_k_9, sizeof(__pyx_k_9), 0, 1, 0},
  {&__pyx_kp_UT_TYPE, __pyx_k_UT_TYPE, sizeof(__pyx_k_UT_TYPE), 1, 1, 1},
  {&__pyx_kp_10, __pyx_k_10, sizeof(__pyx_k_10), 0, 1, 0},
  {&__pyx_kp_11, __pyx_k_11, sizeof(__pyx_k_11), 0, 1, 0},
  {&__pyx_kp_12, __pyx_k_12, sizeof(__pyx_k_12), 0, 1, 0},
  {&__pyx_kp_13, __pyx_k_13, sizeof(__pyx_k_13), 0, 1, 0},
  {&__pyx_kp_14, __pyx_k_14, sizeof(__pyx_k_14), 0, 1, 0},
  {&__pyx_kp_15, __pyx_k_15, sizeof(__pyx_k_15), 0, 1, 0},
  {&__pyx_kp_16, __pyx_k_16, sizeof(__pyx_k_16), 0, 1, 0},
  {&__pyx_kp_17, __pyx_k_17, sizeof(__pyx_k_17), 0, 1, 0},
  {&__pyx_kp_18, __pyx_k_18, sizeof(__pyx_k_18), 0, 1, 0},
  {&__pyx_kp__TYPE_MAP, __pyx_k__TYPE_MAP, sizeof(__pyx_k__TYPE_MAP), 1, 1, 1},
  {&__pyx_kp_Utmp, __pyx_k_Utmp, sizeof(__pyx_k_Utmp), 0, 1, 1},
  {&__pyx_kp_object, __pyx_k_object, sizeof(__pyx_k_object), 1, 1, 1},
  {&__pyx_kp_ut_type, __pyx_k_ut_type, sizeof(__pyx_k_ut_type), 1, 1, 1},
  {&__pyx_kp_ut_pid, __pyx_k_ut_pid, sizeof(__pyx_k_ut_pid), 1, 1, 1},
  {&__pyx_kp_ut_line, __pyx_k_ut_line, sizeof(__pyx_k_ut_line), 1, 1, 1},
  {&__pyx_kp_ut_id, __pyx_k_ut_id, sizeof(__pyx_k_ut_id), 1, 1, 1},
  {&__pyx_kp_ut_user, __pyx_k_ut_user, sizeof(__pyx_k_ut_user), 1, 1, 1},
  {&__pyx_kp_ut_host, __pyx_k_ut_host, sizeof(__pyx_k_ut_host), 1, 1, 1},
  {&__pyx_kp_ut_exit_code, __pyx_k_ut_exit_code, sizeof(__pyx_k_ut_exit_code), 1, 1, 1},
  {&__pyx_kp_ut_session, __pyx_k_ut_session, sizeof(__pyx_k_ut_session), 1, 1, 1},
  {&__pyx_kp_ut_time, __pyx_k_ut_time, sizeof(__pyx_k_ut_time), 1, 1, 1},
  {&__pyx_kp_ut_addr, __pyx_k_ut_addr, sizeof(__pyx_k_ut_addr), 1, 1, 1},
  {&__pyx_kp_ut_user_process, __pyx_k_ut_user_process, sizeof(__pyx_k_ut_user_process), 1, 1, 1},
  {&__pyx_kp_pyutmp, __pyx_k_pyutmp, sizeof(__pyx_k_pyutmp), 1, 1, 1},
  {&__pyx_kp_UtmpFileBase, __pyx_k_UtmpFileBase, sizeof(__pyx_k_UtmpFileBase), 1, 1, 1},
  {&__pyx_kp_UtmpFile, __pyx_k_UtmpFile, sizeof(__pyx_k_UtmpFile), 0, 1, 1},
  {&__pyx_kp___init__, __pyx_k___init__, sizeof(__pyx_k___init__), 0, 1, 1},
  {&__pyx_kp___del__, __pyx_k___del__, sizeof(__pyx_k___del__), 0, 1, 1},
  {&__pyx_kp_rewind, __pyx_k_rewind, sizeof(__pyx_k_rewind), 0, 1, 1},
  {&__pyx_kp__get_next_entry, __pyx_k__get_next_entry, sizeof(__pyx_k__get_next_entry), 0, 1, 1},
  {&__pyx_kp_19, __pyx_k_19, sizeof(__pyx_k_19), 0, 1, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  __pyx_builtin_object = __Pyx_GetName(__pyx_b, __pyx_kp_object); if (!__pyx_builtin_object) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  return 0;
  __pyx_L1_error:;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyutmp_sysv(void); /*proto*/
PyMODINIT_FUNC initpyutmp_sysv(void)
#else
PyMODINIT_FUNC PyInit_pyutmp_sysv(void); /*proto*/
PyMODINIT_FUNC PyInit_pyutmp_sysv(void)
#endif
{
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("pyutmp_sysv", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":51
 *     utmp *getutline(utmp *u)
 * 
 * from enum import Enum             # <<<<<<<<<<<<<<
 * 
 * UT_TYPE = Enum('RUN_LVL',
 */
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp_Enum);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_kp_Enum);
  __pyx_2 = __Pyx_Import(__pyx_kp_enum, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_Enum); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_Enum, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":53
 * from enum import Enum
 * 
 * UT_TYPE = Enum('RUN_LVL',             # <<<<<<<<<<<<<<
 *                'BOOT_TIME',
 *                'NEW_TIME',
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_Enum); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":61
 *                'USER_PROCESS',
 *                'DEAD_PROCESS',
 *                'ACCOUNTING')             # <<<<<<<<<<<<<<
 * 
 * _TYPE_MAP = {RUN_LVL: 'RUN_LVL',
 */
  __pyx_1 = PyTuple_New(9); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp_1);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_kp_1);
  Py_INCREF(__pyx_kp_2);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_kp_2);
  Py_INCREF(__pyx_kp_3);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_kp_3);
  Py_INCREF(__pyx_kp_4);
  PyTuple_SET_ITEM(__pyx_1, 3, __pyx_kp_4);
  Py_INCREF(__pyx_kp_5);
  PyTuple_SET_ITEM(__pyx_1, 4, __pyx_kp_5);
  Py_INCREF(__pyx_kp_6);
  PyTuple_SET_ITEM(__pyx_1, 5, __pyx_kp_6);
  Py_INCREF(__pyx_kp_7);
  PyTuple_SET_ITEM(__pyx_1, 6, __pyx_kp_7);
  Py_INCREF(__pyx_kp_8);
  PyTuple_SET_ITEM(__pyx_1, 7, __pyx_kp_8);
  Py_INCREF(__pyx_kp_9);
  PyTuple_SET_ITEM(__pyx_1, 8, __pyx_kp_9);
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_UT_TYPE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":63
 *                'ACCOUNTING')
 * 
 * _TYPE_MAP = {RUN_LVL: 'RUN_LVL',             # <<<<<<<<<<<<<<
 *              BOOT_TIME: 'BOOT_TIME',
 *              NEW_TIME: 'NEW_TIME',
 */
  __pyx_2 = PyDict_New(); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyInt_FromLong(RUN_LVL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_kp_10) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":64
 * 
 * _TYPE_MAP = {RUN_LVL: 'RUN_LVL',
 *              BOOT_TIME: 'BOOT_TIME',             # <<<<<<<<<<<<<<
 *              NEW_TIME: 'NEW_TIME',
 *              OLD_TIME: 'OLD_TIME',
 */
  __pyx_3 = PyInt_FromLong(BOOT_TIME); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_3, __pyx_kp_11) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":65
 * _TYPE_MAP = {RUN_LVL: 'RUN_LVL',
 *              BOOT_TIME: 'BOOT_TIME',
 *              NEW_TIME: 'NEW_TIME',             # <<<<<<<<<<<<<<
 *              OLD_TIME: 'OLD_TIME',
 *              INIT_PROCESS: 'INIT_PROCESS',
 */
  __pyx_1 = PyInt_FromLong(NEW_TIME); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_kp_12) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":66
 *              BOOT_TIME: 'BOOT_TIME',
 *              NEW_TIME: 'NEW_TIME',
 *              OLD_TIME: 'OLD_TIME',             # <<<<<<<<<<<<<<
 *              INIT_PROCESS: 'INIT_PROCESS',
 *              LOGIN_PROCESS: 'LOGIN_PROCESS',
 */
  __pyx_3 = PyInt_FromLong(OLD_TIME); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_3, __pyx_kp_13) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":67
 *              NEW_TIME: 'NEW_TIME',
 *              OLD_TIME: 'OLD_TIME',
 *              INIT_PROCESS: 'INIT_PROCESS',             # <<<<<<<<<<<<<<
 *              LOGIN_PROCESS: 'LOGIN_PROCESS',
 *              USER_PROCESS: 'USER_PROCESS',
 */
  __pyx_1 = PyInt_FromLong(INIT_PROCESS); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_kp_14) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":68
 *              OLD_TIME: 'OLD_TIME',
 *              INIT_PROCESS: 'INIT_PROCESS',
 *              LOGIN_PROCESS: 'LOGIN_PROCESS',             # <<<<<<<<<<<<<<
 *              USER_PROCESS: 'USER_PROCESS',
 *              DEAD_PROCESS: 'DEAD_PROCESS',
 */
  __pyx_3 = PyInt_FromLong(LOGIN_PROCESS); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_3, __pyx_kp_15) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":69
 *              INIT_PROCESS: 'INIT_PROCESS',
 *              LOGIN_PROCESS: 'LOGIN_PROCESS',
 *              USER_PROCESS: 'USER_PROCESS',             # <<<<<<<<<<<<<<
 *              DEAD_PROCESS: 'DEAD_PROCESS',
 *              ACCOUNTING: 'ACCOUNTING'}
 */
  __pyx_1 = PyInt_FromLong(USER_PROCESS); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_kp_16) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":70
 *              LOGIN_PROCESS: 'LOGIN_PROCESS',
 *              USER_PROCESS: 'USER_PROCESS',
 *              DEAD_PROCESS: 'DEAD_PROCESS',             # <<<<<<<<<<<<<<
 *              ACCOUNTING: 'ACCOUNTING'}
 * 
 */
  __pyx_3 = PyInt_FromLong(DEAD_PROCESS); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_3, __pyx_kp_17) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":71
 *              USER_PROCESS: 'USER_PROCESS',
 *              DEAD_PROCESS: 'DEAD_PROCESS',
 *              ACCOUNTING: 'ACCOUNTING'}             # <<<<<<<<<<<<<<
 * 
 * class Utmp(object):
 */
  __pyx_1 = PyInt_FromLong(ACCOUNTING); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_kp_18) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp__TYPE_MAP, ((PyObject *)__pyx_2)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":73
 *              ACCOUNTING: 'ACCOUNTING'}
 * 
 * class Utmp(object):             # <<<<<<<<<<<<<<
 *     ut_type = UT_UNKNOWN
 *     ut_pid = None
 */
  __pyx_3 = PyDict_New(); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_builtin_object);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_builtin_object);
  __pyx_2 = __Pyx_CreateClass(((PyObject *)__pyx_1), ((PyObject *)__pyx_3), __pyx_kp_Utmp, "pyutmp.pyutmp_sysv"); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":74
 * 
 * class Utmp(object):
 *     ut_type = UT_UNKNOWN             # <<<<<<<<<<<<<<
 *     ut_pid = None
 *     ut_line = None
 */
  __pyx_1 = PyInt_FromLong(UT_UNKNOWN); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_type, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":75
 * class Utmp(object):
 *     ut_type = UT_UNKNOWN
 *     ut_pid = None             # <<<<<<<<<<<<<<
 *     ut_line = None
 *     ut_id = None
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_pid, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":76
 *     ut_type = UT_UNKNOWN
 *     ut_pid = None
 *     ut_line = None             # <<<<<<<<<<<<<<
 *     ut_id = None
 *     ut_user = None
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_line, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":77
 *     ut_pid = None
 *     ut_line = None
 *     ut_id = None             # <<<<<<<<<<<<<<
 *     ut_user = None
 *     ut_host = None
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_id, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":78
 *     ut_line = None
 *     ut_id = None
 *     ut_user = None             # <<<<<<<<<<<<<<
 *     ut_host = None
 *     ut_exit_code = 0
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_user, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":79
 *     ut_id = None
 *     ut_user = None
 *     ut_host = None             # <<<<<<<<<<<<<<
 *     ut_exit_code = 0
 *     ut_session = None
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_host, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":80
 *     ut_user = None
 *     ut_host = None
 *     ut_exit_code = 0             # <<<<<<<<<<<<<<
 *     ut_session = None
 *     ut_time = None
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_exit_code, __pyx_int_0) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":81
 *     ut_host = None
 *     ut_exit_code = 0
 *     ut_session = None             # <<<<<<<<<<<<<<
 *     ut_time = None
 *     ut_addr = None
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_session, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":82
 *     ut_exit_code = 0
 *     ut_session = None
 *     ut_time = None             # <<<<<<<<<<<<<<
 *     ut_addr = None
 *     ut_user_process = False
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_time, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":83
 *     ut_session = None
 *     ut_time = None
 *     ut_addr = None             # <<<<<<<<<<<<<<
 *     ut_user_process = False
 * 
 */
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_addr, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":84
 *     ut_time = None
 *     ut_addr = None
 *     ut_user_process = False             # <<<<<<<<<<<<<<
 * 
 * from pyutmp import UtmpFileBase
 */
  __pyx_1 = __Pyx_PyBool_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_ut_user_process, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_Utmp, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":86
 *     ut_user_process = False
 * 
 * from pyutmp import UtmpFileBase             # <<<<<<<<<<<<<<
 * class UtmpFile(UtmpFileBase):
 * 
 */
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp_UtmpFileBase);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_kp_UtmpFileBase);
  __pyx_2 = __Pyx_Import(__pyx_kp_pyutmp, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_kp_UtmpFileBase); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_UtmpFileBase, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":87
 * 
 * from pyutmp import UtmpFileBase
 * class UtmpFile(UtmpFileBase):             # <<<<<<<<<<<<<<
 * 
 *     def __init__(self):
 */
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_UtmpFileBase); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = __Pyx_CreateClass(((PyObject *)__pyx_3), ((PyObject *)__pyx_1), __pyx_kp_UtmpFile, "pyutmp.pyutmp_sysv"); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":89
 * class UtmpFile(UtmpFileBase):
 * 
 *     def __init__(self):             # <<<<<<<<<<<<<<
 *         setutent()
 * 
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile___init__, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_2, __pyx_kp___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":92
 *         setutent()
 * 
 *     def __del__(self):             # <<<<<<<<<<<<<<
 *         endutent()
 * 
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile___del__, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_2, __pyx_kp___del__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":95
 *         endutent()
 * 
 *     def rewind(self):             # <<<<<<<<<<<<<<
 *         setutent()
 * 
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile_rewind, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_2, __pyx_kp_rewind, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/bmc/src/mystuff/python/pyutmp/pyutmp/pyutmp_sysv.pyx":98
 *         setutent()
 * 
 *     def _get_next_entry(self):             # <<<<<<<<<<<<<<
 *         cdef utmp *entry = getutent()
 *         if entry:
 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_6pyutmp_11pyutmp_sysv_8UtmpFile__get_next_entry, 0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_2, __pyx_kp__get_next_entry, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_UtmpFile, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyutmp.pyutmp_sysv");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "pyutmp_sysv.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;

    #if PY_MAJOR_VERSION < 3
    py_modname = PyString_FromString(modname);
    #else
    py_modname = PyUnicode_FromString(modname);
    #endif
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    result = PyClass_New(bases, dict, name);
    #else
    result = PyObject_CallFunctionObjArgs((PyObject *)&PyType_Type, name, bases, dict, NULL);
    #endif
bad:
    Py_XDECREF(py_modname);
    return result;
}


#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

